import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/components/theme-provider'
import { CustomProvider, useCustomContext } from '@/contexts/ContextCustomization'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  //const {isMonarchLab, setIsMonarchLab}= useCustomContext()


  return (
    <html lang="en" className='h-full'>
     <body
        className={cn(
          'relative h-full font-sans antialiased',
          inter.className
        )}>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            <main className='relative flex flex-col min-h-screen IndexUp'>    
              <Providers>
              <CustomProvider>
                  {<Navbar />}
                  <div className='flex-grow flex-1'>
                    {children}
                  </div>
              </CustomProvider>
              </Providers>
            </main>  
          </ThemeProvider>

        <Toaster position='top-center' richColors/>
      </body>
    </html>
  )
}
